# Generated by Django 6.0.1 on 2026-02-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='comnany',
            new_name='company',
        ),
    ]
